AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  SharedLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: SharedLayer
      ContentUri: layers/
      CompatibleRuntimes:
        - nodejs18.x

Outputs:
  SharedLayer:
    Value: !Ref SharedLayer