AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  SharedLayer:
    Type: String

Resources:
  GetOrders:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs18.x
      Handler: order.handler
      CodeUri: src/
      Layers:
        - !Ref SharedLayer 